BikeWebsite/Controllers/GearController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeWebsite;
using BikeWebsite.Models;

namespace BikeWebsite.Controllers
{
    public class GearController : Controller
    {
        private DBEntities db = new DBEntities();

        // GET: Gear
        public ActionResult Index()
        {
            //var productCategories = db.ProductCategories.Include(p => p.ProductCategory2);
            var productCategories = from d in db.ProductCategories
                                    where d.ProductCategoryID == 2 || d.ProductCategoryID == 3
                                        || d.ProductCategoryID == 4
                                    select d;
            return View(productCategories.ToList());
        }

        public ActionResult Components()
        {
            var components = getResults(2);
            return View(components.ToList());
        }

        public ActionResult Clothing()
        {
            var clothing = getResults(3);
            return View(clothing.ToList());
        }

        public ActionResult Accessories()
        {
            var accessories = getResults(4);
            return View(accessories.ToList());
        }

        public IQueryable<ProductCategory> getResults(int parentProdCatID)
        {
            var results = (from p in db.ProductCategories
                           join v in db.vProductAndDescriptions on p.ProductCategoryID equals v.ProductCategoryID
                           where v.Culture == "en" && v.SellEndDate == null && p.ParentProductCategoryID == parentProdCatID
                           select p).Distinct();

            return results;
        }

        // GET: Gear/Details/5
        public ActionResult Details(string id = null)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //ProductCategory productCategory = db.ProductCategories.Find(id);
            //if (productCategory == null)
            //{
            //    return HttpNotFound();
            //}
            var details = from d in db.Products where d.ProductCategoryID.ToString() == id && d.SellEndDate == null select d;
            return View(details.ToList());
        }

        // GET: Gear/Create
        public ActionResult Create()
        {
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name");
            return View();
        }

        // POST: Gear/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductCategoryID,ParentProductCategoryID,Name,rowguid,ModifiedDate")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.ProductCategories.Add(productCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // GET: Gear/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // POST: Gear/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductCategoryID,ParentProductCategoryID,Name,rowguid,ModifiedDate")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // GET: Gear/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: Gear/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategory productCategory = db.ProductCategories.Find(id);
            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BikeWebsite/Views/Gear/Accessories.cshtml
@model IEnumerable<BikeWebsite.ProductCategory>
@{
    ViewBag.Title = "Accessories";
}

<h2>Accessories</h2>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Details/" + item.ProductCategoryID.ToString())
            </td>
        </tr>
    }
</table>

BikeWebsite/Views/Gear/Clothing.cshtml
@model IEnumerable<BikeWebsite.ProductCategory>
@{
    ViewBag.Title = "Clothing";
}

<h2>Clothing</h2>

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Details/" + item.ProductCategoryID.ToString())
            </td>
        </tr>
    }
</table>

BikeWebsite/Views/Gear/Components.cshtml
@model IEnumerable<BikeWebsite.ProductCategory>
@{
    ViewBag.Title = "Components";
}

<h2>Components</h2>

<table class="table">
    @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Details/" + item.ProductCategoryID.ToString())
            </td>
        </tr>
        }
</table>

BikeWebsite/Views/Gear/Create.cshtml
@model BikeWebsite.ProductCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ParentProductCategoryID, "ParentProductCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentProductCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentProductCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rowguid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rowguid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rowguid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BikeWebsite/Views/Gear/Delete.cshtml
@model BikeWebsite.ProductCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rowguid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rowguid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductCategory2.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCategory2.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BikeWebsite/Views/Gear/Details.cshtml
@model IEnumerable<BikeWebsite.Product>
@{
    ViewBag.Title = "Details";
}

<h2>Product Details</h2>

<div class="table-responsive">
<table class="table">
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.Name)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.ProductNumber)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.Color)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.ListPrice)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.Size)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.Weight)</b></td>
    </tr>
    @foreach (var item in Model)
    {

        var name = item.Name;
        var prodNum = item.ProductNumber;
        var colour = item.Color;
        if (colour == null)
        {
            colour = "N/A";
        }
        var price = item.ListPrice.ToString("c");
        var size = item.Size;
        if (size == null)
        {
            size = "N/A";
        }
        var weight = item.Weight.ToString();
        if (weight == null || weight == "")
        {
            weight = "N/A";
        }
                
        <tr>
            <td>@name</td>
            <td>@prodNum</td>
            <td>@colour</td>
            <td>@price</td>
            @*<td>@Html.DisplayFor(modelItem => item.Size)</td>*@
            <td>@size</td>
            <td>@weight</td>
        </tr>
    }
</table>
</div>

BikeWebsite/Views/Gear/Edit.cshtml
@model BikeWebsite.ProductCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductCategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.ParentProductCategoryID, "ParentProductCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentProductCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentProductCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rowguid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rowguid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rowguid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BikeWebsite/Views/Gear/Index.cshtml
@model IEnumerable<BikeWebsite.ProductCategory>

@{
    ViewBag.Title = "Index";
}

<h1>Amazing Bike Shop</h1>

@MyHelpers.MakeSlider(Model)

<h2>Browse our bike gear</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-xs-12 col-md-4">
            @{
                String[] name = item.Name.Split(' ');
            }
            <a href='@Url.Action(name[0], "Gear")'><img class="showcase" src="@Url.Content("~/Images/"+name[0]+".png")" /></a> <br />
            @Html.ActionLink(item.Name, name[0])
        </div>
    }
</div>

@*
<table class="table table-responsive">
    <tr>
        @foreach (var item in Model)
        {
            <td>
                @{
            String[] name = item.Name.Split(' ');
                }
                <a href='@Url.Action(name[0], "Gear")'><img src="@Url.Content("~/Images/"+name[0]+".png")" /></a> <br />
                @Html.ActionLink(item.Name, name[0])
            </td>
        }
    </tr>
</table>
*@