BikeWebsite/Controllers/BikesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BikeWebsite;
using BikeWebsite.Models;

namespace BikeWebsite.Controllers
{
    public class BikesController : Controller
    {
        private DBEntities db = new DBEntities();

        // GET: Bikes
        public ActionResult Index()
        {
            var productCategories = from p in db.ProductCategories where p.ParentProductCategoryID == 1 select p;
            return View(productCategories.ToList());
        }

        public ActionResult Road()
        {
            var roadBikes = getResults(6);
            return View(roadBikes);
        }

        public ActionResult Mountain()
        {
            var mountainBikes = getResults(5);
            return View(mountainBikes);
        }

        public ActionResult Touring()
        {
            var touringBikes = getResults(7);
            return View(touringBikes);
        }

        public List<bikeListModel> getResults(int productCatID)
        {
            var bikes = (from r in db.vProductAndDescriptions where r.Culture == "en" && r.ProductCategoryID == productCatID && r.SellEndDate == null select new { r.ProductModel, r.Description, r.ProductModelID }).Distinct();
            List<bikeListModel> bikeList = new List<bikeListModel>();
            foreach (var bike in bikes)
            {
                bikeList.Add(new bikeListModel(bike.ProductModel, bike.Description, bike.ProductModelID));
            }
            return bikeList;
        }

        // GET: Bikes/Details/5
        public ActionResult Details(string id = null)
        {
            /*if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);*/

            var details = from d in db.Products where d.ProductModelID.ToString() == id select d;
            return View(details.ToList());
        }

        // GET: Bikes/Create
        public ActionResult Create()
        {
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name");
            return View();
        }

        // POST: Bikes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductCategoryID,ParentProductCategoryID,Name,rowguid,ModifiedDate")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.ProductCategories.Add(productCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // GET: Bikes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // POST: Bikes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductCategoryID,ParentProductCategoryID,Name,rowguid,ModifiedDate")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParentProductCategoryID = new SelectList(db.ProductCategories, "ProductCategoryID", "Name", productCategory.ParentProductCategoryID);
            return View(productCategory);
        }

        // GET: Bikes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: Bikes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductCategory productCategory = db.ProductCategories.Find(id);
            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BikeWebsite/Views/Bikes/Create.cshtml
@model BikeWebsite.ProductCategory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ParentProductCategoryID, "ParentProductCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentProductCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentProductCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rowguid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rowguid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rowguid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BikeWebsite/Views/Bikes/Delete.cshtml
@model BikeWebsite.ProductCategory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductCategory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rowguid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rowguid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductCategory2.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCategory2.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BikeWebsite/Views/Bikes/Details.cshtml
@model IEnumerable<BikeWebsite.Product>
@{
    ViewBag.Title = "Details";
}

<h2>Product Details</h2>

<div class="table-responsive">
    <table class="table">
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.Name)</b></td>
            <td><b>@Html.DisplayNameFor(model => model.ProductNumber)</b></td>
            <td><b>@Html.DisplayNameFor(model => model.Color)</b></td>
            <td><b>@Html.DisplayNameFor(model => model.ListPrice)</b></td>
            <td><b>@Html.DisplayNameFor(model => model.Size)</b></td>
            <td><b>@Html.DisplayNameFor(model => model.Weight)</b></td>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.ProductNumber)</td>
                <td>
                    @if (item.Color == null)
                    {
                        @Html.Raw("N/A")
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.Color)
                    }
                </td>
                <td>@Html.DisplayFor(modelItem => item.ListPrice)</td>
                <td>
                    @if (item.Size == null)
                    {
                        @Html.Raw("N/A")
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.Size)
                        @Html.Raw("cm");
                    }
                </td>
                <td>
                    @if (item.Weight == null)
                    {
                        @Html.Raw("N/A")
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.Weight)
                        @Html.Raw("g");
                    }
                </td>
            </tr>
        }
    </table>
</div>

BikeWebsite/Views/Bikes/Edit.cshtml
@model BikeWebsite.ProductCategory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductCategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.ParentProductCategoryID, "ParentProductCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ParentProductCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ParentProductCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rowguid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rowguid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rowguid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BikeWebsite/Views/Bikes/Index.cshtml
@model IEnumerable<BikeWebsite.ProductCategory>

@{
    ViewBag.Title = "Index";
}

<h1>Amazing Bike Shop</h1>

<div class="col-xs-12 col-md-12">
    @MyHelpers.MakeSlider(Model)
</div>

<h2>Browse our bike models</h2>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-xs-12 col-md-4">
            @{
                String[] name = item.Name.Split(' ');
            }
            <a href='@Url.Action(name[0], "Bikes")'><img class="showcase" src="@Url.Content("~/Images/"+name[0]+".png")" /></a> <br />
            @Html.ActionLink(item.Name, name[0])
        </div>
    }
</div>

@*
<table class="table">
    <tr>
    @foreach (var item in Model) {
        <td>
            @{
                String[] name = item.Name.Split(' ');  
            }
            <a href='@Url.Action(name[0], "Bikes")'><img src="@Url.Content("~/Images/"+name[0]+".png")" /></a> <br />
            @Html.ActionLink(item.Name, name[0])
        </td>
    }
    </tr>
</table>
*@

BikeWebsite/Views/Bikes/Mountain.cshtml
@model IEnumerable<BikeWebsite.Models.bikeListModel>
@{
    ViewBag.Title = "Mountain";
}

<h2>Mountain Bike Model List</h2>
<h3>Conquer any trail, from tame to treacherous with these mountain bikes. Built for the off-road.</h3>
<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.ProductModel, "Details/" + item.ProductModelID.ToString())
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => item.Description)
            </td>
        </tr>
    }
</table>

BikeWebsite/Views/Bikes/Road.cshtml
@model IEnumerable<BikeWebsite.Models.bikeListModel>
@{
    ViewBag.Title = "Road";
}

<h2>Road Bike Model List</h2>
<h3>Passion. Power. Performance. These light, fast bikes have what it takes to keep you out front.</h3>
<table class="table">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.ProductModel, "Details/" + item.ProductModelID.ToString())   
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor( model => item.Description)
                </td>
            </tr>
        }
</table>

BikeWebsite/Views/Bikes/Touring.cshtml
@model IEnumerable<BikeWebsite.Models.bikeListModel>
@{
    ViewBag.Title = "Touring";
}

<h2>Touring Bike Model List</h2>
<h3>Robust, comfortable and capable of carrying heavy loads, these bikes are perfect for road, sport, trail, recumbent or tandem configurations.</h3>
<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.ProductModel, "Details/" + item.ProductModelID.ToString())
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => item.Description)
            </td>
        </tr>
    }
</table>